# Generated by Django 3.1.1 on 2021-01-14 05:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст сообщения')),
                ('is_selected', models.BooleanField(default=False, verbose_name='сообщение отмечено как верное')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='время создания сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='уникальный идентификатор комнаты')),
                ('max_round_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(15)], verbose_name='максимальное время раунда')),
                ('max_rounds_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='максимальное количество раундов')),
                ('max_students_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(2)], verbose_name='максимальное количество студентов')),
                ('is_started', models.BooleanField(default=False, verbose_name='тренинг начался')),
                ('is_finished', models.BooleanField(default=False, verbose_name='тренинг закончился')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round', to='rooms.room', verbose_name='комната, в которой проводится раунд')),
            ],
            options={
                'verbose_name': 'Раунд',
                'verbose_name_plural': 'Раунды',
                'ordering': ('id',),
            },
        ),
    ]
